{% set name = "nbsphinx" %}
{% set version = "0.8.5" %}
{% set sha256 = "c06831d46a768da0b51c3239d45d5a7df2c7e589e5a6d02365cfa49473560ac1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip

  run:
    - python >=3.6
    - docutils
    - jinja2
    - nbconvert
    - nbformat
    - sphinx
    - traitlets

test:
  imports:
    - nbsphinx

about:
  home: http://nbsphinx.rtfd.org/
  license: MIT
  summary: Jupyter Notebook Tools for Sphinx
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ericmjl
    - kmuehlbauer
    - SylvainCorlay
