{% set name = "nbsphinx" %}
{% set version = "0.2.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7c31c9185134b4ce8c347220a9720e5dc59a20584ce993c7c9aa25401b3a1f44

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - docutils
    - jinja2
    - nbconvert
    - nbformat
    - sphinx

test:
  imports:
    - nbsphinx

about:
  home: http://nbsphinx.rtfd.org/
  license: MIT
  summary: 'Jupyter Notebook Tools for Sphinx'
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ericmjl
    - kmuehlbauer
