{% set name = "nbsphinx" %}
{% set version = "0.7.0" %}
{% set sha256 = "77545508fff12fed427fffbd9eae932712fe3db7cc6729b0af5bbd122d7146cf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    - docutils
    - jinja2
    - nbconvert
    - nbformat
    - sphinx

test:
  imports:
    - nbsphinx

about:
  home: http://nbsphinx.rtfd.org/
  license: MIT
  summary: Jupyter Notebook Tools for Sphinx
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ericmjl
    - kmuehlbauer
    - SylvainCorlay
