{% set name = "nbsphinx" %}
{% set version = "0.4.1" %}
{% set sha256 = "f79bcb74b8ff700fa936eca76dd57f3aed8f3d5e3cbb5c441f546a647ada01b8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.5
    - setuptools
    - pip

  run:
    - python >=3.5
    - docutils
    - jinja2
    - nbconvert
    - nbformat
    - sphinx

test:
  imports:
    - nbsphinx

about:
  home: http://nbsphinx.rtfd.org/
  license: MIT
  summary: 'Jupyter Notebook Tools for Sphinx'
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ericmjl
    - kmuehlbauer
    - SylvainCorlay
