travis:
  secure:
    BINSTAR_TOKEN: A8guGMNUaRjN0AJzs2afSOIZrYr4dZyHsSUA25H2wabSsfhHlPKB0GaL2s5GmMrcY26sxNdmTw1DK5/h1PTIpF3u9CP9mwGmPXpxg+DehAxjWrOaqIVsTrbt5mLLLUtDQhVsI41D/SM+4X/aElYX1YSZ4+FBhGAiOYEySKjlk1m5cGpL98n1DT/4rwfbct9u797vKvHBaD4G81jQsdHxB7tpSET9PphFogphozLBWzf3FQoQtxyEgEn2O6axy+MgvBfUuTYdGVibH+QGv7xkPuOXeEZwYMsSml8Yj+WiQRM5P1ZyOncWiMVhf9KcCMMXegfHgl4yqNLwwgSYY/RaV5i/atzXuqGNtswA/hJJ5RS+9F86OLwhTzVDyKTlwja3ayTB+ngXYRaEpqCoqWNW0h04XR/HjTzWwnmE0zwf+psLuPbwkP5uEsNoC0IpTsn3jzUGe80N7MLNTxlvOUaCQ1Bj5J7j3us3MDk2qcWnXI3qZoDH7szp12UpPtdwej/5T7xNsh4NdN1cz8w0dMQL/5F6BT3Br8EFlwkBSFxd6qEz2oMHrJPbazFx4pqH03wf4qtQflSyg8lRTnP0sDEe+nVxnN9w1nVWUCOHXy+ndkfwSgUBbAkvkx6E5eX5JOGh0CFUWddrGqvFc/A25Od+yt5/BmMGNERY1wY1iyq8n1o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
