travis:
  secure:
    BINSTAR_TOKEN: YUOw4VmePPeq7AUWvOQupIuGWCK108y/xwY6bJP4ZGabvq48CN7SHGc6t9A5Tg0TA2lLxOC3u9LpYP3Qewj6wCBOJFxLJ6wYHpMaa6OMu+NUFDwuxREJJBLafyRJZyUcrnl3HP0oJeeTWHSHrz4Rz2UDURRxdqh80QBFgEEXOnwFmWNPykCJbftV3oz6CWlF7nBRl8pm4M/x61H2OXqN+pdtjYgq6HOL4mJlTBrZ+y4SCJsLUTd6N9PxRB0x6qtzFF8cXQS6eVliHmCLGnkFH+xLRBmYPucf4Cv94SdncfuH06zl5p6VAy+kQRtqilkvYJYktuC20ueGyzKdACsto9zwkZpgT/nLuxVHDwkGqB7u77YOJtSeutnbb68/CWwVXe9SLy8ApwCYw2yTXzwT/6LKpgzAwvlaESKH3jUkoB99FPg0Mda+NE+wrvCMDWoFW3njEkDjbzy0Gtdqt+YpJc/x7g0ps4GfccJ1ibp4+5nUgv2l6W7Rv9hTsC9L8PLsq7lTZ1v8ZexMIK+woHR+gf3RGcYWkoLjd6CxTmgOiaSv4XIYXWhlHHimP+aSWkaaFufixxbJzFfPCXLdSj5ofy75kqLf4x7g6yPDHrEbqFaZsO+FUFHfHsmsv8tJrCpGSi5OEm177o6Q37K25RIm/X84Dpvs79/72N9rO1kT6uE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
