travis:
  secure:
    BINSTAR_TOKEN: GPm6b/LntqOnwRMGRAd2uixTXVtTrkukJFOub11OjDq+oRnyzegy/7Eu9RpPMprUVcV2Uni0QHbq7QKCC215PBqVZFjFTLJx1titflRUMiRF8lA0VkBANYqgnVnnJ7k8LlIyAuUQ6tqDThCZE4JpkrNWIox8e9B/dGvWX4CKLnhu4LIsoEqxaoB0UjS3fNBPiChefsiVHI1500njfnjuID3xXPzS3wOgGiUkHNi9kDFSTqXoyYJ0hkQvMEcso5Rtb4cYeZncKtA6nurEcgxh6HlQvRFissU977yNefioH3JCMi33zevErpze7ncR04LTmEE3GNI6SVGo31+3ht/YmFQVPxkMLwAwioEsd7bb8LCnMmv/qjHzMCFkqpzpPD4j5sv7kZP0+PVk44mS16tDt+zD1h6pftVRtH6iR59aevYNlbV2myB5AZROqKu8rejhGEhpd+xev21vPmE7qcYl6gnT9DeM7T7a9zi2Mo9xtpLBuNUK2UdfWHk57QWnWN2SQ10tux64uR1lxLMLjj5Dyq6BA1JmM9n/7zokauXXw/XoIzIOmc0uHoNjacvs/1gVaY8xCYr1SKyUGyJy6Xnh1AoBGMjz11C3uXxw1E8W8jG/BmEp3N+6nLbkR8lTNDF1KEYtZZr7KenpMz5E9kGm9WLGx6w1rD9e+esG5fvBXew=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
